/* Handles dark mode save states (Needs refactoring)*/
$(document).ready(function() {
    var sel = $.cookie("save-darkmode"); // get the cookie
    sel = sel == "true";
    $('.toggle-darkmode').toggleClass("activate-darkmode", sel).on('click', function(e) {
        $('body').toggleClass("dm-bg");
        $('.darkmode-header').toggleClass("dm-header");
        $('.darkmode-menubar').toggleClass("dm-menubar");
        $('.darkmode-block').toggleClass("dm-block");
        $('.darkmode-panel').toggleClass("dm-panel");
        $('.darkmode-txt').toggleClass("dm-txt");
        $('.darkmode-ad').toggleClass("dm-ad");
        $('.darkmode-highlight').toggleClass("dm-highlight");
        $('.darkmode-menubar-l1').toggleClass("dm-menubar-l1");
        $('.darkmode-menubar-l2').toggleClass("dm-menubar-l2");
        $('.darkmode-navsidebar-title').toggleClass("dm-navsidebar-title");
        $('.darkmode-navsidebar-anim').toggleClass("dm-navsidebar-anim");
        $('.darkmode-navsidebar-txt').toggleClass("dm-navsidebar-txt");
        $('.darkmode-buttons').toggleClass("dm-buttons");
        $(".markdown-body").toggleClass("dm-txt");
        $(".markdown-body h2").toggleClass("dm-txt");
        $("#featured-con-block h2").toggleClass("dm-txt");
        $("#featured-con-block p").toggleClass("dm-txt");
		$("#footer-con-container").toggleClass("dm-footer");
		$(".markdown-body li").toggleClass("dm-txt");
		$(".feature-ico-flag").toggleClass("dm-flag");
		/* - */
        $(".compat-table").toggleClass("dm-block");
        $(".compat-table p").toggleClass("dm-txt");
        $(".compat-table a").toggleClass("dm-txt");
        $(".compat-table i").toggleClass("dm-txt");
        $(".compat-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".compat-table th").toggleClass("dm-block");
		$(".compat-table tr").toggleClass("dm-compat-highlight");
        $(".history-table").toggleClass("dm-block");
        $(".history-table p").toggleClass("dm-txt");
        $(".history-table a").toggleClass("dm-txt");
        $(".history-table i").toggleClass("dm-txt");
        $(".history-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".history-table th").toggleClass("dm-block dm-txt");
		$(".history-table td").toggleClass("dm-txt");
		$(".builds-table").toggleClass("dm-block");
		$(".builds-table p").toggleClass("dm-txt");
        $(".builds-table a").toggleClass("dm-txt");
        $(".builds-table i").toggleClass("dm-txt");
		$(".builds-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".builds-table th").toggleClass("dm-block");
		$(".builds-table tr").toggleClass("dm-compat-highlight");
		$(".builds-table td").toggleClass("dm-txt");
        $(".library-table").toggleClass("dm-block");
        $(".divTableHeading").toggleClass("dm-block");
        $(".divTableHeading").toggleClass("dm-txt");
		$(".divTableBody").toggleClass("dm-block");
        $(".divTableBody").toggleClass("dm-txt");
        $(".compat-tx1-criteria").toggleClass("dm-block");
        $(".compat-tx1-criteria").toggleClass("dm-txt");
        $(".compat-status-text").toggleClass("dm-txt");
        $(".compat-search-character").toggleClass("dm-block-search");
        $("#compat-con-pages").toggleClass("dm-block dm-txt");
        $("#compat-author").toggleClass("dm-compat-author");
        $(".nav-links").toggleClass("dm-blog-body dm-txt");
        $(".hentry").toggleClass("dm-blog-body dm-txt");
        $(".entry-header").toggleClass("dm-blog-header");
        $(".entry-footer").toggleClass("dm-blog-footer");
        $(".entry-content h2").toggleClass("dm-blog-h2");
        $(".site-description").toggleClass("dm-blog-sidebar");
        $(".widget-title").toggleClass("dm-blog-sidebar");
        $(".page-header").toggleClass("dm-blog-body");
        $(".page-content").toggleClass("dm-blog-body dm-txt");
		$(".debug-main").toggleClass("dm-block");
    });
    $(".toggle-darkmode").on("click", function() {
        var $this = $(this);
        sel = !sel;
        $this.toggleClass("activate-darkmode", sel);
        $.cookie("save-darkmode", sel, {
            expires: 365,
            path: '/'
        });
    });
});
$(document).ready(function() {
    if ($('.toggle-darkmode').hasClass('activate-darkmode')) {
        $('body').addClass("dm-bg");
        $('.darkmode-header').addClass("dm-header");
        $('.darkmode-menubar').addClass("dm-menubar");
        $('.darkmode-block').addClass("dm-block");
        $('.darkmode-panel').addClass("dm-panel");
        $('.darkmode-txt').addClass("dm-txt");
        $('.darkmode-ad').addClass("dm-ad");
        $('.darkmode-highlight').addClass("dm-highlight");
        $('.darkmode-menubar-l1').addClass("dm-menubar-l1");
        $('.darkmode-menubar-l2').addClass("dm-menubar-l2");
        $('.darkmode-navsidebar-title').addClass("dm-navsidebar-title");
        $('.darkmode-navsidebar-anim').addClass("dm-navsidebar-anim");
        $('.darkmode-navsidebar-txt').addClass("dm-navsidebar-txt");
        $('.darkmode-buttons').addClass("dm-buttons");
        $(".markdown-body").addClass("dm-txt");
        $(".markdown-body h2").addClass("dm-txt");
        $("#featured-con-block h2").addClass("dm-txt");
        $("#featured-con-block p").addClass("dm-txt");
		$(".markdown-body li").addClass("dm-txt");
		$("#footer-con-container").addClass("dm-footer");
		$(".feature-ico-flag").addClass("dm-flag");
		/* - */
        $(".compat-table").toggleClass("dm-block");
        $(".compat-table p").toggleClass("dm-txt");
        $(".compat-table a").toggleClass("dm-txt");
        $(".compat-table i").toggleClass("dm-txt");
        $(".compat-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".compat-table th").toggleClass("dm-block");
		$(".compat-table tr").toggleClass("dm-compat-highlight");
        $(".history-table").toggleClass("dm-block");
        $(".history-table p").toggleClass("dm-txt");
        $(".history-table a").toggleClass("dm-txt");
        $(".history-table i").toggleClass("dm-txt");
        $(".history-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".history-table th").toggleClass("dm-block dm-txt");
		$(".history-table td").toggleClass("dm-txt");
		$(".builds-table").toggleClass("dm-block");
		$(".builds-table p").toggleClass("dm-txt");
        $(".builds-table a").toggleClass("dm-txt");
        $(".builds-table i").toggleClass("dm-txt");
		$(".builds-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".builds-table th").toggleClass("dm-block");
		$(".builds-table tr").toggleClass("dm-compat-highlight");
		$(".builds-table td").toggleClass("dm-txt");
        $(".library-table").toggleClass("dm-block");
        $(".divTableHeading").toggleClass("dm-block");
        $(".divTableHeading").toggleClass("dm-txt");
		$(".divTableBody").toggleClass("dm-block");
        $(".divTableBody").toggleClass("dm-txt");
        $(".compat-tx1-criteria").toggleClass("dm-block");
        $(".compat-tx1-criteria").toggleClass("dm-txt");
        $(".compat-status-text").toggleClass("dm-txt");
        $(".compat-search-character").toggleClass("dm-block-search");
        $("#compat-con-pages").toggleClass("dm-block dm-txt");
        $("#compat-author").toggleClass("dm-compat-author");
        $(".nav-links").toggleClass("dm-blog-body dm-txt");
        $(".hentry").toggleClass("dm-blog-body dm-txt");
        $(".entry-header").toggleClass("dm-blog-header");
        $(".entry-footer").toggleClass("dm-blog-footer");
        $(".entry-content h2").toggleClass("dm-blog-h2");
        $(".site-description").toggleClass("dm-blog-sidebar");
        $(".widget-title").toggleClass("dm-blog-sidebar");
        $(".page-header").toggleClass("dm-blog-body");
        $(".page-content").toggleClass("dm-blog-body dm-txt");
		$(".debug-main").toggleClass("dm-block");
    } else {
        $('body').removeClass("dm-bg");
        $('.darkmode-header').removeClass("dm-header");
        $('.darkmode-menubar').removeClass("dm-menubar");
        $('.darkmode-block').removeClass("dm-block");
        $('.darkmode-panel').removeClass("dm-panel");
        $('.darkmode-txt').removeClass("dm-txt");
        $('.darkmode-ad').removeClass("dm-ad");
        $('.darkmode-highlight').removeClass("dm-highlight");
        $('.darkmode-menubar-l1').removeClass("dm-menubar-l1");
        $('.darkmode-menubar-l2').removeClass("dm-menubar-l2");
        $('.darkmode-navsidebar-title').removeClass("dm-navsidebar-title");
        $('.darkmode-navsidebar-anim').removeClass("dm-navsidebar-anim");
        $('.darkmode-navsidebar-txt').removeClass("dm-navsidebar-txt");
        $('.darkmode-buttons').removeClass("dm-buttons");
        $(".markdown-body").removeClass("dm-txt");
        $(".markdown-body h2").removeClass("dm-txt");
        $("#featured-con-block h2").removeClass("dm-txt");
        $("#featured-con-block p").removeClass("dm-txt");
		$(".markdown-body li").removeClass("dm-txt");
		$("#footer-con-container").removeClass("dm-footer");
		$(".feature-ico-flag").removeClass("dm-flag");
		/* - */
        $(".compat-table").removeClass("dm-block");
        $(".compat-table p").removeClass("dm-txt");
        $(".compat-table a").removeClass("dm-txt");
        $(".compat-table i").removeClass("dm-txt");
        $(".compat-table tr:nth-child(2n+1)").removeClass("dm-block");
        $(".compat-table th").removeClass("dm-block");
		$(".compat-table tr").removeClass("dm-compat-highlight");
        $(".history-table").removeClass("dm-block");
        $(".history-table p").removeClass("dm-txt");
        $(".history-table a").removeClass("dm-txt");
        $(".history-table i").removeClass("dm-txt");
        $(".history-table tr:nth-child(2n+1)").removeClass("dm-block");
        $(".history-table th").removeClass("dm-block dm-txt");
		$(".history-table td").removeClass("dm-txt");
        $(".library-table").removeClass("dm-block");
		$(".builds-table").toggleClass("dm-block");
		$(".builds-table p").removeClass("dm-txt");
        $(".builds-table a").removeClass("dm-txt");
        $(".builds-table i").removeClass("dm-txt");
		$(".builds-table tr:nth-child(2n+1)").toggleClass("dm-block");
        $(".builds-table th").toggleClass("dm-block");
		$(".builds-table tr").toggleClass("dm-compat-highlight");
		$(".builds-table td").removeClass("dm-txt");
        $(".divTableHeading").removeClass("dm-block");
        $(".divTableHeading").removeClass("dm-txt");
		$(".divTableBody").removeClass("dm-block");
        $(".divTableBody").removeClass("dm-txt");
        $(".compat-tx1-criteria").removeClass("dm-block");
        $(".compat-tx1-criteria").removeClass("dm-txt");
        $(".compat-status-text").removeClass("dm-txt");
        $(".compat-search-character").removeClass("dm-block-search");
        $("#compat-con-pages").removeClass("dm-block dm-txt");
        $("#compat-author").removeClass("dm-compat-author");
        $(".nav-links").removeClass("dm-blog-body dm-txt");
        $(".hentry").removeClass("dm-blog-body dm-txt");
        $(".entry-header").removeClass("dm-blog-header");
        $(".entry-footer").removeClass("dm-blog-footer");
        $(".entry-content h2").removeClass("dm-blog-h2");
        $(".site-description").removeClass("dm-blog-sidebar");
        $(".widget-title").removeClass("dm-blog-sidebar");
        $(".page-header").removeClass("dm-blog-body");
        $(".page-content").removeClass("dm-blog-body dm-txt");
		$(".debug-main").removeClass("dm-block");
    }
});