services:
  php:
    image: rpcs3/web:dev
    build: .
    container_name: rpcs3-web

    ports:
      - "8080:80"

    volumes:
      - ./public_html:/var/www/html
      - ./configs:/var/www/configs:ro
