<script data-cfasync="false" src='/lib/js/jquery.js'></script>
<script data-cfasync="false" src='/lib/js/jquery-cookie.js'></script>
<script data-cfasync="false" src='/lib/js/darkmode.js'></script>
<script data-cfasync="false" src='/lib/js/main.js'></script>
<link rel="stylesheet" href="/lib/css/html.css?v=4"/>
<link rel="stylesheet" href="/lib/css/anim.css?v=4"/>
<link rel="stylesheet" href="/lib/css/main.css?v=4"/>
<link rel="stylesheet" href="/lib/css/darkmode.css?v=4"/>
<link rel="stylesheet" href="/lib/css/menu.css?v=4"/>
<link rel="stylesheet" href="/lib/css/scale.css?v=4"/>
<link rel="stylesheet" href="/lib/css/debug.css?v=4"/>
