<?php

function cacheRoadmap() {
	$content = file_get_contents("https://github.com/RPCS3/rpcs3/wiki/Roadmap");

	if ($content) {
		$start = "<div id=\"wiki-body\" class=\"mt-4 flex-auto min-width-0 gollum-markdown-content instapaper_body\">";
		$end = "</div>";

		$roadmap = explode($end, explode($start, $content)[1])[0];

		$path = realpath(__DIR__)."/../../cache/";
		$file = fopen("{$path}roadmap_cached.php", "w");
		fwrite($file, "<!-- This file is automatically generated every hour -->\n{$roadmap}");
		fclose($file);
	}
}

// Cache Roadmap (Running every hour)
cacheRoadmap();

?>
